// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File".
// You do not need to add suppressions to this file manually.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", Scope = "member")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvvmValidation.RuleValidationResultExtensions.#Combine(MvvmValidation.RuleValidationResult,MvvmValidation.RuleValidationResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "MvvmValidation.RuleValidationResultExtensions.#Combine(MvvmValidation.RuleValidationResult,MvvmValidation.RuleValidationResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvvmValidation.ValidationResult.#ToString(MvvmValidation.IValidationResultFormatter)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvvmValidation.ValidationResultExtensions.#Combine(MvvmValidation.ValidationResult,MvvmValidation.ValidationResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "MvvmValidation.ValidationResultExtensions.#Combine(MvvmValidation.ValidationResult,MvvmValidation.ValidationResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvvmValidation.RuleResultExtensions.#Combine(MvvmValidation.RuleResult,MvvmValidation.RuleResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "MvvmValidation.RuleResultExtensions.#Combine(MvvmValidation.RuleResult,MvvmValidation.RuleResult)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "MvvmValidation.ValidationHelperExtensions.#AddChildValidatable(MvvmValidation.ValidationHelper,System.Linq.Expressions.Expression`1<System.Func`1<MvvmValidation.IValidatable>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvvmValidation.ValidationHelperExtensions.#AddChildValidatable(MvvmValidation.ValidationHelper,System.Linq.Expressions.Expression`1<System.Func`1<MvvmValidation.IValidatable>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "MvvmValidation.ValidationHelperExtensions.#AddChildValidatableCollection(MvvmValidation.ValidationHelper,System.Linq.Expressions.Expression`1<System.Func`1<System.Collections.Generic.IEnumerable`1<MvvmValidation.IValidatable>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvvmValidation.ValidationHelperExtensions.#AddChildValidatableCollection(MvvmValidation.ValidationHelper,System.Linq.Expressions.Expression`1<System.Func`1<System.Collections.Generic.IEnumerable`1<MvvmValidation.IValidatable>>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "1", Scope = "member", Target = "MvvmValidation.ValidationHelperExtensions.#AddRequiredRule(MvvmValidation.ValidationHelper,System.Linq.Expressions.Expression`1<System.Func`1<System.Object>>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MvvmValidation.ValidationHelperExtensions.#AddRequiredRule(MvvmValidation.ValidationHelper,System.Linq.Expressions.Expression`1<System.Func`1<System.Object>>,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "MvvmValidation.IAsyncValidationRule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1040:AvoidEmptyInterfaces", Scope = "type", Target = "MvvmValidation.IValidationRule")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "type", Target = "MvvmValidation.ValidationException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2237:MarkISerializableTypesWithSerializable", Scope = "type", Target = "MvvmValidation.ValidationException")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2243:AttributeStringLiteralsShouldParseCorrectly")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvvmValidation.ValidationHelper.#AddAsyncRule(System.Object,System.Func`1<System.Threading.Tasks.Task`1<MvvmValidation.RuleResult>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "MvvmValidation.ValidationHelper.#AddAsyncRule(System.Func`1<System.Threading.Tasks.Task`1<MvvmValidation.RuleResult>>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "MvvmValidation.ValidationScope.#GetResult()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "MvvmValidation.ValidationHelperExtensions.#ValidateThisProperty(MvvmValidation.ValidationHelper,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "MvvmValidation.Internal.Guard.FormatMessageWithCollerInfo(System.String,System.String,System.String,System.Int32)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotOutOfRange`1(System.Boolean,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object[])", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotOutOfRange`1(System.Boolean,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "MvvmValidation.Internal.Guard.FormatMessageWithCollerInfo(System.String,System.String,System.String,System.Int32)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNullOrEmpty(System.String,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object[])", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNullOrEmpty(System.String,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "MvvmValidation.Internal.Guard.FormatMessageWithCollerInfo(System.String,System.String,System.String,System.Int32)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNullOrEmpty(System.String,System.Linq.Expressions.Expression`1<System.Func`1<System.String>>,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object[])", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNullOrEmpty(System.String,System.Linq.Expressions.Expression`1<System.Func`1<System.String>>,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "MvvmValidation.Internal.Guard.FormatMessageWithCollerInfo(System.String,System.String,System.String,System.Int32)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNull`1(!!0,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object[])", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNull`1(!!0,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1303:Do not pass literals as localized parameters", MessageId = "MvvmValidation.Internal.Guard.FormatMessageWithCollerInfo(System.String,System.String,System.String,System.Int32)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNull`1(!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object[])", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNull`1(!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "System.Runtime.CompilerServices")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNull`1(!!0,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNullOrEmpty(System.String,System.Linq.Expressions.Expression`1<System.Func`1<System.String>>,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNullOrEmpty(System.String,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotOutOfRange`1(System.Boolean,System.Linq.Expressions.Expression`1<System.Func`1<!!0>>,System.String,System.String,System.String,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Globalization", "CA1305:SpecifyIFormatProvider", MessageId = "System.String.Format(System.String,System.Object)", Scope = "member", Target = "MvvmValidation.Internal.Guard.#NotNull`1(!!0,System.String,System.String,System.String,System.Int32)")]
